export { default as DashboardPage } from './DashboardPage'
export { default as AssetsPage } from './AssetsPage'
export { default as AssetCreatePage } from './AssetCreatePage'
export { default as AssetEditPage } from './AssetEditPage'
export { default as AIPage } from './AIPage'
export { default as NotFoundPage } from './NotFoundPage'
